export function createOverlayElements () {
  return {
    metaN: document.getElementById('meta-n') as HTMLElement,
    wall: document.getElementById('m-wall') as HTMLElement,
    render: document.getElementById('m-render') as HTMLElement,
    budget: document.getElementById('m-budget') as HTMLElement,
    display: document.getElementById('m-display') as HTMLElement,
    target: document.getElementById('m-target') as HTMLElement,
    skip: document.getElementById('m-skip') as HTMLElement,
    cap: document.getElementById('m-cap') as HTMLElement,
    zoomDistance: document.getElementById('m-zoom-distance') as HTMLElement,
    renderPolicy: document.getElementById('m-render-policy') as HTMLElement,
    policyDensity: document.getElementById('m-policy-density') as HTMLElement,
    policyReason: document.getElementById('m-policy-reason') as HTMLElement,
    quad: document.getElementById('m-quad') as HTMLElement,
    rep: document.getElementById('m-rep') as HTMLElement,
    link: document.getElementById('m-link') as HTMLElement,
    grav: document.getElementById('m-grav') as HTMLElement,
    canvas: document.getElementById('m-canvas') as HTMLElement,
    linesCull: document.getElementById('m-lines-cull') as HTMLElement,
    lines: document.getElementById('m-lines') as HTMLElement,
    pointsCull: document.getElementById('m-points-cull') as HTMLElement,
    pointsTileBudget: document.getElementById('m-points-tile-budget') as HTMLElement,
    points: document.getElementById('m-points') as HTMLElement,
    impostorTilesBin: document.getElementById('m-impostor-tiles-bin') as HTMLElement,
    impostorTilesResolve: document.getElementById('m-impostor-tiles-resolve') as HTMLElement,
    impostorAnchorsFill: document.getElementById('m-impostor-anchors-fill') as HTMLElement,
    impostorAnchorsMaterialize: document.getElementById('m-impostor-anchors-materialize') as HTMLElement,
    alpha: document.getElementById('m-alpha') as HTMLElement,
    dpr: document.getElementById('m-dpr') as HTMLElement,
  }
}

export type OverlayElements = ReturnType<typeof createOverlayElements>

export function createControlElements () {
  return {
    n: document.getElementById('c-n') as HTMLSelectElement,
    nButtons: [...document.querySelectorAll<HTMLButtonElement>('#n-buttons button')],
    data: document.getElementById('c-data') as HTMLSelectElement,
    seed: document.getElementById('c-seed') as HTMLInputElement,
    webgpu: document.getElementById('c-webgpu') as HTMLInputElement,
    msaa: document.getElementById('c-msaa') as HTMLInputElement,
    msaaRow: document.getElementById('row-msaa') as HTMLLabelElement,
    adpr: document.getElementById('c-adpr') as HTMLInputElement,
    adprRow: document.getElementById('row-adpr') as HTMLLabelElement,
    blend: document.getElementById('c-blend') as HTMLSelectElement,
    blendRow: document.getElementById('row-blend') as HTMLLabelElement,
    frameCap: document.getElementById('c-frame-cap') as HTMLSelectElement,
    theme: document.getElementById('btn-theme') as HTMLButtonElement,
    density: document.getElementById('btn-density') as HTMLButtonElement,
    edges: document.getElementById('btn-edges') as HTMLButtonElement,
    lod: document.getElementById('btn-lod') as HTMLButtonElement,
    lanes: document.getElementById('btn-lanes') as HTMLButtonElement,
    tilt: document.getElementById('btn-tilt') as HTMLButtonElement,
    modeReadout: document.getElementById('mode-readout') as HTMLElement,
    depthPreset: document.getElementById('c-depth-preset') as HTMLSelectElement,
    depthStrength: document.getElementById('c-depth-strength') as HTMLInputElement,
    depthStrengthValue: document.getElementById('v-depth-strength') as HTMLElement,
    depthSize: document.getElementById('c-depth-size') as HTMLInputElement,
    depthSizeValue: document.getElementById('v-depth-size') as HTMLElement,
    depthBrightness: document.getElementById('c-depth-brightness') as HTMLInputElement,
    depthBrightnessValue: document.getElementById('v-depth-brightness') as HTMLElement,
    depthOpacity: document.getElementById('c-depth-opacity') as HTMLInputElement,
    depthOpacityValue: document.getElementById('v-depth-opacity') as HTMLElement,
    depthMoat: document.getElementById('c-depth-moat') as HTMLInputElement,
    depthMoatValue: document.getElementById('v-depth-moat') as HTMLElement,
    depthHighlight: document.getElementById('c-depth-highlight') as HTMLInputElement,
    depthHighlightValue: document.getElementById('v-depth-highlight') as HTMLElement,
    depthShadow: document.getElementById('c-depth-shadow') as HTMLInputElement,
    depthShadowValue: document.getElementById('v-depth-shadow') as HTMLElement,
    depthSaturation: document.getElementById('c-depth-saturation') as HTMLInputElement,
    depthSaturationValue: document.getElementById('v-depth-saturation') as HTMLElement,
    borderTreatment: document.getElementById('c-border-treatment') as HTMLSelectElement,
    tileBudget: document.getElementById('c-tile-budget') as HTMLInputElement,
    tileBudgetValue: document.getElementById('v-tile-budget') as HTMLElement,
    tileSize: document.getElementById('c-tile-size') as HTMLInputElement,
    tileSizeValue: document.getElementById('v-tile-size') as HTMLElement,
    tileMaxScale: document.getElementById('c-tile-max-scale') as HTMLInputElement,
    tileMaxScaleValue: document.getElementById('v-tile-max-scale') as HTMLElement,
    sim: document.getElementById('c-sim') as HTMLInputElement,
    simRow: document.getElementById('row-sim') as HTMLLabelElement,
    record: document.getElementById('btn-record') as HTMLButtonElement,
    recordStatus: document.getElementById('record-status') as HTMLElement,
    replay: document.getElementById('btn-replay') as HTMLButtonElement,
    replayStatus: document.getElementById('replay-status') as HTMLElement,
    bakeLabel: document.getElementById('c-bake-label') as HTMLInputElement,
    bakePointsOnly: document.getElementById('c-bake-points-only') as HTMLInputElement,
    bake: document.getElementById('btn-bake') as HTMLButtonElement,
    bakeStatus: document.getElementById('bake-status') as HTMLElement,
    load: document.getElementById('btn-load') as HTMLButtonElement,
    loadStatus: document.getElementById('load-status') as HTMLElement,
    galleryTab: document.getElementById('gallery-tab') as HTMLButtonElement,
    gallery: document.getElementById('preset-gallery') as HTMLDivElement,
    galleryClose: document.getElementById('gallery-close') as HTMLButtonElement,
    presetCards: [...document.querySelectorAll<HTMLButtonElement>('.preset-card')],
    cosmicBegin: document.getElementById('cosmic-begin') as HTMLButtonElement,
    cosmicIntro: document.getElementById('cosmic-intro') as HTMLDivElement,
    cosmicIntroLayer: document.getElementById('cosmic-intro-renderer') as HTMLDivElement,
  }
}

export type ControlElements = ReturnType<typeof createControlElements>

export function createFocusElements () {
  return {
    title: document.getElementById('focus-title') as HTMLElement,
    subtitle: document.getElementById('focus-subtitle') as HTMLElement,
    node: document.getElementById('focus-node') as HTMLElement,
    degree: document.getElementById('focus-degree') as HTMLElement,
    links: document.getElementById('focus-links') as HTMLElement,
    kind: document.getElementById('focus-kind') as HTMLElement,
    group: document.getElementById('focus-group') as HTMLElement,
    company: document.getElementById('focus-company') as HTMLElement,
    strength: document.getElementById('focus-strength') as HTMLElement,
    overview: document.getElementById('btn-focus-overview') as HTMLButtonElement,
    neighbors: document.getElementById('btn-focus-neighbors') as HTMLButtonElement,
    step: document.getElementById('btn-focus-step') as HTMLButtonElement,
  }
}

export type FocusElements = ReturnType<typeof createFocusElements>
