export const simulationDefaultConfigValues = {
  simulationDecay: 500,
  alphaStopThreshold: 0.05,
  physicsTickRate: 0,
  frameRateLimit: 0,
  frameRateHeadroomFps: 0,
  debugFrameTrace: false,
  simulationGravity: 0.25,
  simulationCenter: 0,
  simulationRepulsion: 1.0,
  simulationRepulsionTheta: 1.15,
  simulationLinkSpring: 1,
  simulationLinkDistance: 10,
  simulationLinkDistRandomVariationRange: [1, 1.2],
  simulationRepulsionFromMouse: 2,
  simulationFriction: 0.85,
  simulationCluster: 0.1,
  enableRightClickRepulsion: false,
  onSimulationStart: undefined,
  onSimulationTick: undefined,
  onSimulationEnd: undefined,
  onSimulationPause: undefined,
  onSimulationUnpause: undefined,
}
